### ISSUE TITLE
Generate a graph representation of the results for querying / grouping by rules, stack, rule categories or tags...

### ISSUE THREAD

**Issue by scarbonell-vmware** [vmware-tanzu/cloud-suitability-analyzer#102]
Generate a graph representation of applications scanned to the rules they have triggered.
App to stack, app to rules, app to score...Anything that could help querying / grouping apps with a common set of challenges for modernization.

It could be a simple export button that would export a .graphml vs the typical .csv file from a global result list.
The graph could be imported into a graphDB like Neo4j for further analysis and visualization.

"Tell me what apps use some api or triggered some IIS dependencies rule or some specific websphere modules across the 100 apps I have scanned with total score higher than 8"

**Comment by stevew00ds** [comment]
For the time being, you'll have to rely on SQL to the SQL-Lite database.
