### ISSUE TITLE
False positive in java-security rule

### ISSUE THREAD

**Issue by p3pijn** [vmware-tanzu/cloud-suitability-analyzer#104]
The regex to match `java.security` is too broad and also matches non-cloud violating classes, like `java.security.Principal`. (https://github.com/vmware-tanzu/cloud-suitability-analyzer/blob/master/rules/java-security.yaml#L19)

This rule seems to be about matching usage of certificate-related functionality.
Suggestion, make the regex more precise by replacing `java.security` with:
- `java.security.PrivateKey`
- `java.security.PublicKey`
- `java.security.KeyStore`
- `java.security.Certificate`

See the Java documentation https://docs.oracle.com/javase/8/docs/api/java/security/package-summary.html

**Comment by stevew00ds** [comment]
Thank you for suggestion. Putting into project.
