### ISSUE TITLE
False positives in java-servlet rule

### ISSUE THREAD

**Issue by p3pijn** [vmware-tanzu/cloud-suitability-analyzer#105]
This rule with regex `import javax.servlet.` is too broad. It also matches classes that are often used in modern Spring apps, like `HttpServletRequest` (https://www.baeldung.com/spring-reading-httpservletrequest-multiple-times).

Suggestion: make the rule more specific to the use of the "legacy" Java Servlet class: `import javax.servlet.Servlet` or match specific classes that are considered J2EE style servlet usage.

**Comment by stevew00ds** [comment]
Thank you for the suggestion. Putting into project.
