### ISSUE TITLE
False positives in dotnet-ipv4-addresses

### ISSUE THREAD

**Issue by p3pijn** [vmware-tanzu/cloud-suitability-analyzer#106]
This rule looks both in `.cs` files, as well as in config files, like `.config, .json, .yml, etc`.
Matches in `.cs` files are typically true positives, but matches in the config files have a very high false positive rate.

Suggestion is to split this rule into 2 rules:
- Rule that looks in `.cs` files only (similar to  how that is done for `java-hardIP`)
- Rule that looks in `.config, .json, .xml, etc` files

In this way users can decide which of the 2 to enable (or both) in their context.

**Comment by stevew00ds** [comment]
Thank you for suggesting, putting into project.
