### ISSUE TITLE
Convert existing .NET xml regex rules to XPath

### ISSUE THREAD

**Issue by jszod** [vmware-tanzu/cloud-suitability-analyzer#14]

**Comment by jszod** [comment]
There are approximately 7 rules in total to be converted
Two rules have been converted to date

- [ ] Identify rules to be converted
- [ ] Convert the remaining rules

**Comment by chrisumbel** [comment]
Converted: config-encryption.yaml
config-security.yaml
config-sessionState.yaml
dotnet-database-access.yaml
dotnet-ISAPI-Filters-config.yaml
dotnet-FileCacheModule.yaml
dotnet-HttpCacheModule.yaml
dotnet-RequestFilteringModule.yaml
dotnet-StaticCompressionModule.yaml
dotnet-StaticFileModule.yaml
dotnet-TokenCacheModule.yaml
dotnet-UriCacheModule.yaml
dotnet-WindowsAuth-config.yaml
