### ISSUE TITLE
[Inquiry] Where to find the documentation referred for the "Find JAX-RS" rule?

### ISSUE THREAD

**Issue by tomasged** [vmware-tanzu/cloud-suitability-analyzer#149]
I just stumbled upon this tool and I'm evaluating it. I saw this rule:
https://github.com/vmware-tanzu/cloud-suitability-analyzer/blob/master/rules/java-jaxrs-import.yaml

, and I'm just curious about what's the issue. I'm struggling to find the need to identify the JAX-RS imports for cloud suitability purposes, so I wonder if someone knows what it's meant with: "Refer to platform documentation", in the advice section.

Thank you and best regards.

**Comment by rahulkj** [comment]
The context is related to the application being supported on cloudfoundry or not. Since RS is typically used with J2EE, and could potentially have an app server dependency, it is getting flagged here by the scans. It could be a false positive based on the environment your application run in
