### ISSUE TITLE
Summary/Scoring Summary filter is not filtering contents

### ISSUE THREAD

**Issue by jszod** [vmware-tanzu/cloud-suitability-analyzer#80]
On Summary/Scoring screen, the filter has no effect on display in all columns

To recreate:
* Select filter
* Enter name of a displayed app in the list
* All grid contents disappear

**Comment by iRohitBajaj** [comment]
Fixed as part of https://github.com/vmware-tanzu/cloud-suitability-analyzer/pull/86
