### ISSUE TITLE
bug: Data screen - table footer is not "reactive" and is not visible

### ISSUE THREAD

**Issue by jszod** [vmware-tanzu/cloud-suitability-analyzer#83]
The footer is not behaving in a reactive mode. It is not visible unless the browser window is scrolled down

To recreate:
* Click data tab
* Table footer is not visible
* Scroll browser window down to see table footer

**Comment by iRohitBajaj** [comment]
Fixed as part of https://github.com/vmware-tanzu/cloud-suitability-analyzer/pull/86
