### ISSUE TITLE
bug: Data/All Findings - Id filter not filtering

### ISSUE THREAD

**Issue by jszod** [vmware-tanzu/cloud-suitability-analyzer#85]
To recreate:
* Click on Data main tab
* Click on All Findings sub tab
* In the ID columns, click filter icon
* Add one of the displayed values, 
* Screen shows blank contents

**Comment by iRohitBajaj** [comment]
Fixed as part of https://github.com/vmware-tanzu/cloud-suitability-analyzer/pull/86
