### ISSUE TITLE
VMware OSS UX - Main Table not utilizing full screen

### ISSUE THREAD

**Issue by Turbots** [vmware-tanzu/cloud-suitability-analyzer#87]
When loading a report, the main table contents are not utilizing the full screen. Screenshot attached
![image](https://user-images.githubusercontent.com/1653600/123289925-25c8a980-d511-11eb-81a1-c8d82356faba.png)

Even when content is too wide, I have to scroll in the table, rather than the table filling the whole width of the page (and then scrolling)

**Comment by iRohitBajaj** [comment]
Fixed as part of https://github.com/vmware-tanzu/cloud-suitability-analyzer/pull/89
